f = open('openFile.txt', 'r')
data1 = f.read(3)
data = f.read()
print(data)
print(data1)

print(".............. Radeline method  ...............")
f = open('openFile.txt', 'r')
data1 = f.readline()
data2 = f.readline()
print(data1)
print(data2)
f.close()

print(".............. Radelines method  ...............")
f = open('openFile.txt', 'r')
data1 = f.readlines()
print(data1)
f.close()